name: C++ CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configuración del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalación de dependencias
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      # Paso 3: Crear directorio para la compilación
      - name: Create build directory
        run: mkdir -p build

      # Paso 4: Configuración con CMake
      - name: Configure with CMake
        run: cmake -S . -B build

      # Paso 5: Compilación del proyecto
      - name: Build project
        run: cmake --build build

      # Paso 6: Ejecutar pruebas (si las tienes configuradas en CMake)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
